// ============================================================================
// THE MISSING DEGREE OF FREEDOM IS A REPARAMETRISATION — so the chart covers everything, up to it.
//
// THE QUESTION, asked by Eric and much better than the answer I had been circling: "can this missing
// dimension be a reparametrisation of the same curve?"
//
// It can, and it is. PH is a property of the PARAMETRISATION rather than of the point set (Kalkan et
// al. §2 — the parabola is not PH and a rational reparametrisation of it is), so a Möbius map of the
// parameter t acts on the variety of degree-4 parametrised rational PH curves and preserves both the
// degree and the PH condition. That action is PGL(2,ℝ), three-dimensional, generated by
//
//     t ↦ t + b        shift
//     t ↦ a t          scale
//     t ↦ t/(1 − εt)   the projective one
//
// MEASURED, at a member of the chart, as the component of each generator's tangent lying OUTSIDE the
// chart's own twelve directions:
//
//     shift        0.00 %      already in the chart
//     scale        0.00 %      already in the chart
//     projective  12.3 %       NOT in the chart
//
// and the span goes 12 → 13, which is exactly the variety's dimension. So:
//
//     the λ-chart's twelve directions plus the projective reparametrisation are the whole thing.
//
// WHAT THAT MEANS, and it deflates a day of work in the best way. The gap is not missing SHAPES. Every
// degree-4 rational PH curve is, up to how it is traversed, already reachable. What the chart cannot
// do is re-traverse a curve it already has.
//
// AND IT EXPLAINS THE SIGNATURE THAT KEPT SHOWING UP. A projective reparametrisation of a member has
// deg w = 4 rather than 1 — homogenising to degree 4 multiplies the denominator by (1 − εt)³ — which is
// exactly what the missing-direction walk found when it landed on four-pole curves, and what the
// continuation did when it left deg w = 1. Same event, now named. Note also that the reparametrised
// member has the SAME rank 11: it is the same curve, so of course it is the same kind of point.
//
// WHY THIS MATTERS DIFFERENTLY FOR DIFFERENT USES. For an editor that cares about shape, coverage is
// complete and the gap is bookkeeping. For anything that cares about the speed profile — motion
// planning, arc-length parametrisation, a rotation-minimising frame in time — a reparametrisation is
// not nothing, and the missing freedom is real.
// ============================================================================
import { describe, it, expect } from 'vitest'
import {
  type MultiPoleParams,
  denominatorOf, familyBasis, packSpinor, toMember, unpackSpinor,
} from '../rationalPHMultiPoleSpatial'
import { jacobian, layoutFor, pack, rankOf, residual, scaleDirection, unpack } from '../rationalPHVariety'
import { orthonormalise, polySqrt } from '../sp11RationalPH'
import type { Quat } from '../quaternion'

const L = layoutFor(4)
const D = 4
const ZERO = (k: number): Quat[] => Array.from({ length: k }, () => ({ u: 0, v: 0, p: 0, q: 0 }))

const SEED: MultiPoleParams = (() => {
  const base: MultiPoleParams = { A: ZERO(3), roots: [1.7], lambdas: [Math.tan((35 * Math.PI) / 180)] }
  const B = familyBasis(base)
  const x = new Array<number>(12).fill(0)
  B.forEach((b, i) => {
    const a = 1.3 * Math.sin(1.7 * i + 0.6)
    for (let j = 0; j < 12; j++) x[j] += a * b[j]
  })
  return { ...base, A: unpackSpinor(x) }
})()

const pMul = (a: readonly number[], b: readonly number[]): number[] => {
  const o = new Array<number>(a.length + b.length - 1).fill(0)
  a.forEach((x, i) => b.forEach((y, j) => { o[i + j] += x * y }))
  return o
}
const pAdd = (a: readonly number[], b: readonly number[]): number[] =>
  Array.from({ length: Math.max(a.length, b.length) }, (_, i) => (a[i] ?? 0) + (b[i] ?? 0))
const pDeriv = (a: readonly number[]): number[] => (a.length < 2 ? [0] : a.slice(1).map((c, i) => c * (i + 1)))
const evalAt = (a: readonly number[], t: number): number => a.reduceRight((s, c) => s * t + c, 0)
const trim = (a: readonly number[]): number => {
  const s = Math.max(...a.map(Math.abs), 1e-300)
  let top = a.length - 1
  while (top > 0 && Math.abs(a[top]) < 1e-10 * s) top--
  return top
}

const M0 = toMember(SEED)
const P0 = (M0.p as number[][]).map((a) => a.slice())
const W0 = (M0.w as number[]).slice()
const S0 = (M0.sigma as number[]).slice()
const X0 = pack({ p: P0, w: W0, sigma: S0 }, L)

/**
 * A polynomial of degree ≤ D reparametrised HOMOGENEOUSLY: Σ f_k t^k (1 − εt)^{D−k}. Every term has
 * degree exactly D, so the degree is preserved — which is the whole reason the action stays inside
 * degree-4 rational Béziers.
 */
function reparametrise(f: readonly number[], eps: number): number[] {
  let out = new Array<number>(D + 1).fill(0)
  for (let k = 0; k <= D; k++) {
    const c = f[k] ?? 0
    if (c === 0) continue
    let term: number[] = [1]
    for (let j = 0; j < D - k; j++) term = pMul(term, [1, -eps])
    const shifted = new Array<number>(k).fill(0).concat(term)
    out = pAdd(out, shifted.map((v) => c * v))
  }
  return out.slice(0, D + 1)
}
const affine = (f: readonly number[], kind: 'shift' | 'scale', e: number): number[] => {
  const out = new Array<number>(D + 1).fill(0)
  for (let k = 0; k <= D; k++) {
    const c = f[k] ?? 0
    if (c === 0) continue
    if (kind === 'scale') { out[k] += c * Math.pow(1 + e, k); continue }
    let term: number[] = [1]
    for (let j = 0; j < k; j++) term = pMul(term, [e, 1])
    term.forEach((v, i) => { out[i] += c * v })
  }
  return out
}

/** Rebuild the point (p, w, σ) after a reparametrisation, taking σ's branch from the original. */
function pointFrom(p: number[][], w: number[]): number[] | null {
  const wD = pDeriv(w)
  const N = p.map((pk) => {
    const a = pMul(pDeriv(pk), w), b = pMul(pk, wD)
    return Array.from({ length: Math.max(a.length, b.length) }, (_, i) => (a[i] ?? 0) - (b[i] ?? 0))
  })
  const q = N.reduce<number[]>((acc, n) => pAdd(acc, pMul(n, n)), [0])
  const root = polySqrt(q.slice(0, 13), 1e-6)
  if (!root) return null
  const sigma = evalAt(root, 0) * evalAt(S0, 0) < 0 ? root.map((v) => -v) : root
  return pack({ p, w, sigma }, L)
}
const projective = (eps: number): number[] | null =>
  pointFrom(P0.map((a) => reparametrise(a, eps)), reparametrise(W0, eps))
const affinePoint = (kind: 'shift' | 'scale', e: number): number[] | null =>
  pointFrom(P0.map((a) => affine(a, kind, e)), affine(W0, kind, e))

/** The chart's own tangent at the member: every parameter the construction has. */
function chartTangent(): number[][] {
  const xs = packSpinor(SEED.A)
  const cols: number[][] = []
  const packOf = (prm: MultiPoleParams): number[] => {
    const m = toMember(prm)
    return pack({ p: m.p as number[][], w: m.w as number[], sigma: m.sigma as number[] }, L)
  }
  const central = (f: (d: number) => number[]): void => {
    const hi = f(1e-5), lo = f(-1e-5)
    cols.push(hi.map((q, i) => (q - lo[i]) / 2e-5))
  }
  const onto = (x: readonly number[], roots: readonly number[], lam: readonly number[]): number[] => {
    const B = familyBasis({ A: unpackSpinor(new Array<number>(12).fill(0)), roots, lambdas: lam })
    const o = new Array<number>(12).fill(0)
    for (const b of B) {
      const d = x.reduce((s, q, i) => s + q * b[i], 0)
      for (let i = 0; i < 12; i++) o[i] += d * b[i]
    }
    return o
  }
  for (const b of familyBasis(SEED)) {
    central((d) => packOf({ ...SEED, A: unpackSpinor(xs.map((q, i) => q + d * b[i])) }))
  }
  central((d) => {
    const lam = [SEED.lambdas[0] + d]
    return packOf({ ...SEED, A: unpackSpinor(onto(xs, SEED.roots, lam)), lambdas: lam })
  })
  central((d) => {
    const rt = [SEED.roots[0] + d]
    return packOf({ ...SEED, A: unpackSpinor(onto(xs, rt, SEED.lambdas)), roots: rt })
  })
  const w = denominatorOf(SEED.roots)
  for (let axis = 0; axis < 3; axis++) {
    const v = new Array<number>(L.unknowns).fill(0)
    for (let i = 0; i < w.length && i <= L.degP; i++) v[axis * (L.degP + 1) + i] = w[i]
    cols.push(v)
  }
  return cols
}

const SD = scaleDirection(X0, L)
const stripScale = (cols: number[][]): number[][] =>
  orthonormalise(cols.map((c) => {
    const d = c.reduce((s, v, i) => s + v * SD[i], 0)
    return c.map((v, i) => v - d * SD[i])
  }), 1e-8)

const RAW = chartTangent()
const CHART = stripScale(RAW)

/** Fraction of a direction lying outside the chart's tangent, after the scale gauge is removed. */
function outsideChart(v: readonly number[]): number {
  let r = v.slice()
  const n = Math.hypot(...r) || 1
  r = r.map((q) => q / n)
  const d0 = r.reduce((s, q, i) => s + q * SD[i], 0)
  r = r.map((q, i) => q - d0 * SD[i])
  const before = Math.hypot(...r) || 1
  for (const c of CHART) {
    const d = r.reduce((s, q, i) => s + q * c[i], 0)
    r = r.map((q, i) => q - d * c[i])
  }
  return Math.hypot(...r) / before
}
const tangentOf = (f: (e: number) => number[] | null, h = 1e-4): number[] | null => {
  const a = f(h), b = f(-h)
  return a && b ? a.map((q, i) => (q - b[i]) / (2 * h)) : null
}

describe('the missing degree of freedom', () => {
  it('a reparametrised member is still on the variety, and still the same kind of point', () => {
    for (const eps of [0.02, 0.05, 0.1]) {
      const y = projective(eps)
      expect(y).not.toBeNull()
      const scale = Math.max(...y!.map(Math.abs)) ** 4
      expect(Math.max(...residual(y!, L).map(Math.abs)) / scale).toBeLessThan(1e-13)
      // deg w goes 1 → 4: homogenising to degree 4 multiplies the denominator by (1 − εt)³
      expect(trim(unpack(y!, L).w)).toBe(4)
      // and it is the SAME CURVE, so it is the same kind of point: rank 11, as at the member
      expect(rankOf(jacobian(y!, L))).toBe(11)
    }
    expect(trim(W0)).toBe(1)
    expect(rankOf(jacobian(X0, L))).toBe(11)
  })

  it('THE TWO AFFINE REPARAMETRISATIONS ARE ALREADY IN THE CHART', () => {
    for (const kind of ['shift', 'scale'] as const) {
      const v = tangentOf((e) => affinePoint(kind, e))
      expect(v).not.toBeNull()
      expect(outsideChart(v!)).toBeLessThan(1e-6)          // measured 0.00 %
    }
    expect(CHART.length).toBe(12)
  })

  it('AND THE PROJECTIVE ONE IS NOT — it is the thirteenth direction', () => {
    const v = tangentOf((e) => projective(e))
    expect(v).not.toBeNull()
    expect(outsideChart(v!)).toBeGreaterThan(0.05)         // measured 12.3 %
    // the chart's twelve plus this one span the variety's full dimension
    expect(stripScale([...RAW, v!]).length).toBe(13)
    expect(L.unknowns - L.equations - 1).toBe(13)
  })

  it('so the chart covers every degree-4 rational PH curve UP TO REPARAMETRISATION', () => {
    const v = tangentOf((e) => projective(e))!
    const withRepar = stripScale([...RAW, v]).length
    expect(withRepar).toBe(L.unknowns - L.equations - 1)   // 13 = 13, nothing else is missing
    expect(withRepar - CHART.length).toBe(1)               // and exactly one direction was added
  })
})
