// Clean, self-contained B-spline core: evaluation and knot insertion for a
// scalar function or a plain / rational / complex-rational curve, open or
// periodic, over a scalar-field abstraction.
export * from './types'
export * from './complex'
export * from './basis'
export * from './coeffs'
export * from './evaluate'
export * from './indexing'
export * from './insert'
export * from './elevate'
export * from './bernstein'
export * from './complexBernstein'
export * from './curvature'
export * from './phCurvature'
export * from './phClosure'
export * from './phDrag'
export * from './phCurveConstruction'
export * from './phFit'
export * from './curvatureFamilies'
export * from './curvatureDrag'
export * from './trustRegionOptimizer'
export * from './trustRegionBanded'
export * from './phCurveBoundDrag'
export * from './gradient'
export * from './curvatureHessian'
export * from './linalg'
export * from './banded'
export * from './optimize'
export * from './barrierOptimizer'
export * from './bandedPrimalDual'
export * from './symmetryReduction'
export * from './curvatureProblem'
export * from './complexRational'
export * from './function'
export * from './structuralScale'
export * from './phValueBound'
