// ============================================================================
// Planar PH curves of degree 7, and the CONTROL-POINT problem.
//
// The generator w is a cubic with Bernstein coefficients w₀…w₃ (four complex = 8 real);
// r′ = w² has degree 6, so the curve has degree 7 and eight control points. With the
// translation that is 10 real degrees of freedom, and the planar gauge w ↦ −w is
// DISCRETE, so it costs none:
//
//     dim = 2k + 2 = 10        k = deg w + 1 = 4
//
// Five control points cost 2 each, so v_max = 5 and dim = 0. And the solution is
// UNIQUE — proved by construction, because the cascade never solves an equation:
//
//     N₀ = w₀²                       →  w₀ = √N₀    the ± IS the gauge
//     N₁ = w₀w₁                      →  w₁ = N₁/w₀
//     N₂ = (2/5)w₀w₂ + (3/5)w₁²      →  w₂
//     N₃ = (1/10)w₀w₃ + (9/10)w₁w₂   →  w₃
//
// A square root and three divisions. Nothing is left over, so there is no closing
// system and nothing can branch — and every five points work, the only failure being
// N₀ = 0 (a first leg of length zero). Contrast BOTH neighbours:
//
//   * the same curve through five POINTS (phPlanarSepticInterp) — eight solutions,
//     because the unknown ratios enter quadratically instead of by division;
//   * the same control-point problem in SPACE (septicCascadeDegree.test.ts) — there the
//     stage is polar(A₀,·): ℍ → ℝ³, four unknowns for three equations, so each stage
//     leaves a free parameter, and three of them close into a degree-8 resultant with
//     0, 2, 4 or 6 real answers. The plane's stage is multiplication by w₀ on ℂ, which
//     is invertible. The branching in space is manufactured by the CONTINUOUS gauge.
//
// The smallest case of the cascade is the oldest planar PH fact there is: at degree 3
// it reads N₁² = N₀N₂, the three legs in geometric progression.
// ============================================================================
import { type Complex, cadd, csub, cmul, cdiv, cscale, cnorm } from './complex'

/** The generator's four Bernstein coefficients. */
export type Spinor4 = readonly [Complex, Complex, Complex, Complex]

export interface PlanarSepticSolution {
  generator: Spinor4
  /** The curve's eight control points, P₀ first. */
  controlPoints: Complex[]
  /** ∫|r′|dt, exact (the parametric speed is the polynomial |w|²). */
  arcLength: number
  /** R = ∫|κ|ds, the survey's fairness selector. Numerical. */
  rotationIndex: number
}

const C0: Complex = { re: 0, im: 0 }

/** The principal square root. Either branch is fine — the choice IS the gauge. */
export function csqrt(z: Complex): Complex {
  const r = cnorm(z)
  if (r === 0) return C0
  const re = Math.sqrt(Math.max(0, (r + z.re) / 2))
  const im = (z.im < 0 ? -1 : 1) * Math.sqrt(Math.max(0, (r - z.re) / 2))
  return { re, im }
}

const BIN3 = [1, 3, 3, 1]
const BIN6 = [1, 6, 15, 20, 15, 6, 1]

/**
 * The hodograph's seven Bernstein coefficients, N = w². These are the curve's LEGS up
 * to the degree: P_{j+1} − P_j = N_j / 7.
 */
export function hodographCoefficients(w: Spinor4): Complex[] {
  const N: Complex[] = []
  for (let r = 0; r <= 6; r++) {
    let s: Complex = C0
    for (let j = Math.max(0, r - 3); j <= Math.min(3, r); j++) {
      s = cadd(s, cscale(cmul(w[j], w[r - j]), (BIN3[j] * BIN3[r - j]) / BIN6[r]))
    }
    N.push(s)
  }
  return N
}

/** The eight control points of the curve generated by w and starting at p0. */
export function controlPointsOf(w: Spinor4, p0: Complex): Complex[] {
  const N = hodographCoefficients(w)
  const P: Complex[] = [p0]
  for (let j = 0; j < 7; j++) P.push(cadd(P[j], cscale(N[j], 1 / 7)))
  return P
}

/** de Casteljau on the control points — used for drawing. */
export function bezierAt(cps: readonly Complex[], t: number): Complex {
  let a = [...cps]
  while (a.length > 1) {
    const b: Complex[] = []
    for (let i = 0; i + 1 < a.length; i++) b.push(cadd(cscale(a[i], 1 - t), cscale(a[i + 1], t)))
    a = b
  }
  return a[0]
}

/** w evaluated at t, de Casteljau in the cubic Bernstein basis. */
export function generatorAt(w: Spinor4, t: number): Complex {
  return bezierAt(w as readonly Complex[], t)
}

/**
 * ∫₀¹|r′|dt. The parametric speed of a PH curve is |w|², a genuine polynomial, so this
 * is exact: the Bernstein coefficients of |w|² summed and divided by the degree + 1.
 */
export function arcLengthOf(w: Spinor4): number {
  let total = 0
  for (let r = 0; r <= 6; r++) {
    let s = 0
    for (let j = Math.max(0, r - 3); j <= Math.min(3, r); j++) {
      const a = w[j]
      const b = w[r - j]
      // Re(w_j · conj(w_l)) — the imaginary parts cancel over the symmetric sum.
      s += ((BIN3[j] * BIN3[r - j]) / BIN6[r]) * (a.re * b.re + a.im * b.im)
    }
    total += s
  }
  return total / 7
}

/**
 * R = ∫|κ|ds. For a planar PH curve κ·ds = 2·Im(w̄ w′)/|w|² dt, which stays finite
 * wherever w ≠ 0, so a plain Simpson rule is enough for a readout.
 */
export function rotationIndexOf(w: Spinor4, samples = 400): number {
  // w′ in the quadratic Bernstein basis: 3(w_{j+1} − w_j).
  const dw = [0, 1, 2].map((j) => cscale(csub(w[j + 1], w[j]), 3))
  const at = (t: number): number => {
    const v = generatorAt(w, t)
    const d = bezierAt(dw, t)
    const n = v.re * v.re + v.im * v.im
    if (n < 1e-30) return 0
    return Math.abs(2 * (v.re * d.im - v.im * d.re)) / n
  }
  let sum = at(0) + at(1)
  for (let i = 1; i < samples; i++) sum += (i % 2 ? 4 : 2) * at(i / samples)
  return (sum / (3 * samples))
}

export function solutionFrom(w: Spinor4, p0: Complex): PlanarSepticSolution {
  return {
    generator: w,
    controlPoints: controlPointsOf(w, p0),
    arcLength: arcLengthOf(w),
    rotationIndex: rotationIndexOf(w),
  }
}

/**
 * THE CASCADE. Five prescribed control points P₀…P₄ ↦ the one curve that has them.
 *
 * Returns null only when the first leg has length zero, which is the single
 * configuration the construction cannot start from.
 */
export function planarSepticFromControlPoints(
  P: readonly Complex[],
): PlanarSepticSolution | null {
  if (P.length < 5) return null
  const N = [0, 1, 2, 3].map((j) => cscale(csub(P[j + 1], P[j]), 7))
  if (cnorm(N[0]) < 1e-14) return null

  const w0 = csqrt(N[0])
  const w1 = cdiv(N[1], w0)
  //  N₂ = (2/5)w₀w₂ + (3/5)w₁²
  const w2 = cdiv(csub(N[2], cscale(cmul(w1, w1), 3 / 5)), cscale(w0, 2 / 5))
  //  N₃ = (1/10)w₀w₃ + (9/10)w₁w₂
  const w3 = cdiv(csub(N[3], cscale(cmul(w1, w2), 9 / 10)), cscale(w0, 1 / 10))

  return solutionFrom([w0, w1, w2, w3], P[0])
}

/**
 * THE SPLIT PRESCRIPTION: P₀,P₁,P₂ and P₆,P₇ — five control points again, ten conditions
 * again, and FOUR curves instead of one.
 *
 * What changes is not how many conditions but WHICH. Three at the start fix the legs
 * N₀,N₁; two at the end fix N₆; and the gap from P₂ to P₆ yields only their SUM,
 * N₂+N₃+N₄+N₅ = 7(P₆−P₂), where the consecutive set had four separate legs. So:
 *
 *     w₀ = √N₀                          the ± here is the whole gauge
 *     w₁ = N₁/w₀
 *     w₃ = ±√N₆                         a GENUINE branch — the gauge is already spent
 *     (3/5)w₂² + B·w₂ + (C − D) = 0     quadratic, so two more
 *
 *     B = (2/5)w₀ + (9/10)w₁ + w₃       C = (3/5)w₁² + (1/10)w₀w₃ + (2/5)w₁w₃
 *
 * Two signs × two roots = four, and the count for other five-point subsets runs 1, 2, 4
 * or 8 by the same reasoning (a gap that stops short of N₆ stays LINEAR in w₃; one that
 * swallows N₆ = w₃² turns quadratic; the count is the product).
 *
 * AND IT IS WELL CONDITIONED, unlike the consecutive set. There w₃ came out of
 * 10·(N₃ − …)/w₀, giving gain ≈ 10; here it is a square root of prescribed data and the
 * factor never appears. Measured: dragging P₆ by five leg-lengths changes arc length by
 * 1.5×, where the consecutive set changes it by 370×.
 *
 * THE TWO w₂-BRANCHES ARE ISOMETRIC. Arc length is ∫|w|² = G₂₂|w₂|² + 2Re(w̄₂k) + const
 * with k = Σ_{j≠2} G₂ⱼwⱼ, and the difference between the two roots works out to
 * Re(Δ·conj(2a·k − G₂₂·B))/a², which vanishes identically because 2a·k = G₂₂·B — both
 * equal (6/175)w₀ + (27/350)w₁ + (3/35)w₃. So the pair differs in shape at exactly equal
 * length, which is the planar echo of the spatial cubic fibre's isometry.
 *
 * Returns the branches in a deterministic order; a caller drawing them must still track
 * identity across a drag (the ± of a principal square root is not continuous).
 */
export function planarSepticFromSplitControlPoints(
  P: readonly Complex[],
): PlanarSepticSolution[] {
  if (P.length < 5) return []
  const [p0, p1, p2, p6, p7] = P
  const N0 = cscale(csub(p1, p0), 7)
  const N1 = cscale(csub(p2, p1), 7)
  const N6 = cscale(csub(p7, p6), 7)
  const D = cscale(csub(p6, p2), 7)
  if (cnorm(N0) < 1e-14) return []

  const w0 = csqrt(N0)
  const w1 = cdiv(N1, w0)
  const a: Complex = { re: 3 / 5, im: 0 }
  const out: PlanarSepticSolution[] = []
  const seen: Spinor4[] = []

  for (const s of [1, -1]) {
    const w3 = cscale(csqrt(N6), s)
    const B = cadd(cadd(cscale(w0, 2 / 5), cscale(w1, 9 / 10)), w3)
    const C = cadd(
      cadd(cscale(cmul(w1, w1), 3 / 5), cscale(cmul(w0, w3), 1 / 10)),
      cscale(cmul(w1, w3), 2 / 5),
    )
    const disc = csqrt(csub(cmul(B, B), cscale(cmul(a, csub(C, D)), 4)))
    for (const t of [1, -1]) {
      const w2 = cdiv(cadd(cscale(B, -1), cscale(disc, t)), cscale(a, 2))
      const w: Spinor4 = [w0, w1, w2, w3]
      if (!w.every((z) => Number.isFinite(z.re) && Number.isFinite(z.im))) continue
      // A vanishing discriminant (or N₆ = 0) merges a pair; do not list it twice.
      if (seen.some((v) => v.every((z, j) => cnorm(csub(z, w[j])) < 1e-10))) continue
      seen.push(w)
      out.push(solutionFrom(w, p0))
    }
  }
  return out
}
